### ISSUE TITLE
immortalized legend ahri

### ISSUE THREAD

**Issue by Srakopuzik** [hydy100/R3nzSkin#10]
Can you pls add 3 form of immortalized legend ahri separately?

**Comment by lwlxsgnet** [comment]
> Can you pls add 3 form of immortalized legend ahri separately?

maybe not. refer to https://github.com/hydy100/R3nzSkin/issues/7#issuecomment-2183859268

**Comment by ConeDjordjic** [comment]
> * If you think it's fine, you can go ahead and close this issue again.
> 
> ![image](https://private-user-images.githubusercontent.com/62869308/342110799-16e11471-2345-440c-a3e9-510369e11f10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDg3ODAsIm5iZiI6MTcxOTI0ODQ4MCwicGF0aCI6Ii82Mjg2OTMwOC8zNDIxMTA3OTktMTZlMTE0NzEtMjM0NS00NDBjLWEzZTktNTEwMzY5ZTExZjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE3MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmUyZWY3YzE5NTgwODM1MzdiNjJlNGFjZmY0N2FkMzk2YmJiMjUwODNkNjFkOTQxNTQ0OWU4N2U0ZjZkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_zxYkxY0IlqYTXlJLQuMPCKeLmzLogks7M6wEmB02Q)

quick question i was wondering if it's doable to fix dawnbringer riven? iirc the server sends the assets or something so idk

**Comment by Srakopuzik** [comment]
Work perfectly, thank you man!
