### ISSUE TITLE
Lags in game , not smooth

### ISSUE THREAD

**Issue by gucan98** [hydy100/R3nzSkin#119]
Hey guys i wonder if you have same issues as me i've been ranking up and losing all my games i stop use R3NZ SKIN and my game finnaly normal i'm mad the program made me lag so much the game feel so smooth without it is that normal or not ?

**Comment by vergil123-beep** [comment]
i think its normal for me

**Comment by xnfelix666** [comment]
i have the same issue, lots of crashes and when i press home key to uninject , game feels 10 times smoother, this hasnt happened before this last update
