### ISSUE TITLE
目前七个号封了五个，两个三年 三个七天

### ISSUE THREAD

**Issue by IssacClarkIsimula** [hydy100/R3nzSkin#136]
rt，已删

**Comment by Eff0rtly** [comment]
> 不会提issues可以不提，要反馈好好反馈，封了多久，怎么封的(追封的还是玩着玩着封的)，哪个版本封的说清楚就好了，而不是特此给我发个通告我谢谢您嘞，通篇提取不出来一个对开发者有帮助的信息，用个免费软件给你牛大了。好用的时候屁都不放，不好用的时候莫须有的罪名也来了，哪个版本封号，封多久我能不清楚吗？(截止目前我编译的国服版本不开其他东西能封三年我把电脑吃了)更了不封的版本也不看，描述也不看，主打的就是白嫖不愿意承担任何风险。
建忠国人是这样的

**Comment by Eff0rtly** [comment]
@hydy100 别生气了 13亿 难免出点nt

**Comment by IssacClarkIsimula** [comment]
不咋会用github，之前看R3nz那里大家都是在issue直接反馈的；封号时间应该是版本更新前两天（29-30号），14.16这个版本，号都是后来登录兑换那个战斗之夜口令才发现被封了七天或者三年，封的时间统一在下午两点半；封三年我就开了这个，seraphine（一个也在github更新的lol工具箱）和这个，不会存在开什么脚本外挂啥的；对于使用您软件有封号风险我是知晓并自愿承担风险的，昨天发这个的目的是为了给同样在使用插件的大伙一个参考，确实是封了这么多号这么多天；我个人是很感谢在R3不更的情况下有作者这样的好人无私为大伙继续更新，更不会说因为封号了就怨作者啥的blabla，只是就目前情况来看我不敢在大号用了删了插件，并和大伙分享下目前的情况；最后给作者道个歉，没有考虑到在作者辛勤无私奉献的作品下这样留言对创作者来说是怎样的感受，也希望作者不要因为我的言论停止了这个优秀插件的更新（更新的很快，17版本一出就同步更新了）
