### ISSUE TITLE
China.Injection.ReSkin_new.7z封号了，请求更新

### ISSUE THREAD

**Issue by moshidada** [hydy100/R3nzSkin#222]
China.Injection.ReSkin_new.7z封号了，请求更新

**Comment by moshidada** [comment]
是的！
![Uploading QQ20241115-213014.png…]()

**Comment by moshidada** [comment]
![QQ20241115-213014](https://github.com/user-attachments/assets/586aa979-b89f-45ae-9f53-7f90279d53e1)

**Comment by moshidada** [comment]
> 先这样吧，缓一缓，用的人不晓得有多少，发了没多久的估计又得到了和谐的捏，有点想跑路了。

别呀，大佬

**Comment by moshidada** [comment]
> > > 先这样吧，缓一缓，用的人不晓得有多少，发了没多久的估计又得到了和谐的猜测，有点想跑路了。
> > 
> > 
> > 别呀，大佬
> 
> 目前一切正常，不知道你怎么操作的确保，封号期间未使用过其他软件么，另外我测试半天是个乌龙。

啊？一直用的这个版本！不知道啥情况，好像是追封

**Comment by ChenTGui** [comment]
腾讯的检测机制一般不会触发，除非是对面举报你，一旦你被举报，基本100%会被封，除非可以过tp的检测

**Comment by Grape20** [comment]
这一个月基本每天都在用，没有被封号；这么说举报的时候备注换肤还真有点道理。
