### ISSUE TITLE
No dialog box RiotServersReSkin

### ISSUE THREAD

**Issue by carryDS** [hydy100/R3nzSkin#247]
when I run the skin injector as administrator there is no dialog box. So, I tried Reskin in administrator and when I start the injector, the injector status say working but my game crash automatically, any reasons ?

**Comment by carryDS** [comment]
I'm sending you a video to show you my problem.
[https://we.tl/t-Yt7hChi1H9](url)

**Comment by Nirvanazero** [comment]
When I inject I get error 48 8B 1D E8 48 8B 7B

**Comment by carryDS** [comment]
Its work when i change computer
