### ISSUE TITLE
a questiom

### ISSUE THREAD

**Issue by latte-11** [hydy100/R3nzSkin#76]
hello,bro.Can version 14.14 of R3nzSKIN be used for version 14.15, as I noticed that you haven't released a new version yet

**Comment by liu-yang666588** [comment]
> 请查看版本中 14.14 版本的最后描述。

14.15版本用不了啊，需要更新

**Comment by latte-11** [comment]
> 请查看版本中 14.14 版本的最后描述。

Okay, I've seen it. Thank you, author
