### ISSUE TITLE
next bug occurs. Now every other players have default skin

### ISSUE THREAD

**Issue by eternal-art** [hydy100/R3nzSkin#89]
after u inject it to the game, after you die u will still have selected skin on but now every other player in the game's skin changes to the default one

**Comment by Shraim64** [comment]
is it fixed yet?

**Comment by eternal-art** [comment]
@Shraim64 all hopes are in @hydy100 . The fact that a few hours after the LoL update, hydy also tried to update the skin changer as well is respect. We just have to wait.
